"""First migration

Revision ID: 4bf3a9441e73
Revises: 
Create Date: 2023-06-19 13:31:55.579325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf3a9441e73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Client',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('date_include', sa.DateTime(), nullable=True),
    sa.Column('date_update', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Client_email'), 'Client', ['email'], unique=False)
    op.create_index(op.f('ix_Client_name'), 'Client', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Client_name'), table_name='Client')
    op.drop_index(op.f('ix_Client_email'), table_name='Client')
    op.drop_table('Client')
    # ### end Alembic commands ###
