"""Change table Client to client

Revision ID: 6e8d10dff9ab
Revises: 4bf3a9441e73
Create Date: 2023-06-19 13:34:09.742020

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6e8d10dff9ab'
down_revision = '4bf3a9441e73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('date_include', sa.DateTime(), nullable=True),
    sa.Column('date_update', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_email'), 'client', ['email'], unique=False)
    op.create_index(op.f('ix_client_name'), 'client', ['name'], unique=False)
    op.drop_index('ix_Client_email', table_name='Client')
    op.drop_index('ix_Client_name', table_name='Client')
    op.drop_table('Client')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Client',
    sa.Column('id', sa.BIGINT(), server_default=sa.text('nextval(\'"Client_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('date_include', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_update', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Client_pkey')
    )
    op.create_index('ix_Client_name', 'Client', ['name'], unique=False)
    op.create_index('ix_Client_email', 'Client', ['email'], unique=False)
    op.drop_index(op.f('ix_client_name'), table_name='client')
    op.drop_index(op.f('ix_client_email'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
