version: "3.7"

services:

  kbgptapi:
    build: ./
    container_name: kbgpt-api
    image: kbgpt-api
    restart: always
    environment:
      - APP_ENVIRONMENT=${APP_ENVIRONMENT}
    ports:
      - "8085:80"
    volumes:
      - ./files:/api/files
    logging:
      driver: json-file
      options:
        max-size: "10m" # Tamanho máximo do arquivo de log (exemplo: 10 megabytes)
        max-file: "5" # Número máximo de arquivos de log a serem mantidos (exemplo: 3)
